version: '3.8'

services:

  phpfpm:
    build:
      context: .
      dockerfile: build/docker/php/Dockerfile
    image: phpfpm
    container_name: app-phpfpm

    working_dir: /var/www/
    volumes:
      - ./src/bones:/var/www

    networks:
      - appdata

  web:
    image: nginx:1.19-alpine
    container_name: app-web

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./config/docker/nginx/sites:/etc/nginx/conf.d:rw
      - ./src/bones:/var/www

    networks:
      - appdata


networks:
  appdata:
    driver: bridge