version: '3'

services:

  web:
    image: nginx:1.19-alpine
    container_name: web
    depends_on:
      - phpfpm
    environment:
      DEBUG: 1
    ports:
      - '8150:80'
    volumes:
      - ./config/docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/laravel:/var/www:delegated
    restart: on-failure

  phpfpm:
    build:
      context: .
      dockerfile: build/dev/php/7.4/fpm/Dockerfile
    container_name: phpfpm\
    environment:
      DEBUG: 1
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-laraval}
      DB_USERNAME: ${DB_USER:-developer}
      DB_PASSWORD: ${DB_PASS:-developer
    volumes:
      - ./src/laravel:/var/www:delegated
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: build/dev/mysql/8.0/Dockerfile
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-laravel}
      MYSQL_USER: ${DB_USER:-developer}
      MYSQL_PASSWORD: ${DB_PASS:-developer}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-developer}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - dbdata:/var/lib/mysql