version: '3'

services:

  # Nginx
  web:
    image: nginx:1.19-alpine
    container_name: web
    depends_on:
      - phpfpm

    environment:
      DEBUG: 1

    networks:
      - appdata
    ports:
      - '8150:80'

    volumes:
      - ./config/docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/laravel:/var/www:delegated

    restart: on-failure

  # PHP 7.4 FPM
  phpfpm:
    build:
      context: .
      dockerfile: build/dev/php/7.4/fpm/Dockerfile
    container_name: phpfpm

    environment:
      DEBUG: 1

    networks:
      - appdata

    volumes:
      - ./src/laravel:/var/www:delegated

    restart: on-failure


networks:
  appdata:
    driver: bridge
