version: '3'

services:

  # Nginx
  web:
    image: nginx:1.19-alpine
    container_name: web
    depends_on:
      - phpfpm

    environment:
      DEBUG: 1

    networks:
      - appdata
    ports:
      - '80:80'

    volumes:
      - ./config/docker/nginx/darkstar.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/darkstar:/var/www:delegated

    restart: on-failure

  # PHP 7.4 FPM
  phpfpm:
    build:
      context: .
      dockerfile: build/dev/php/7.4/fpm/Dockerfile
      args:
        - PHP_VERSION=$PHP_VERSION
    container_name: phpfpm

    environment:
      DEBUG: 1

    networks:
      - appdata

    volumes:
      - ./src/darkstar:/var/www:delegated

    restart: on-failure


networks:
  appdata:
    driver: bridge
